name: polyaxon-assignment7
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pillow=7.1.2
  - flask=1.1.2
  - tensorflow=2.1.0
  - pip=19.0.3
  - pip:
    - pandas==1.0.5
    - scikit-learn==0.23.1
    - waitress==1.4.4
